name: CI
#on: push
on:
  workflow_dispatch:
   inputs:
      mservice:
        description: 'Microservice'
        default: 'PromotionNoCoupon'
        required: true

  schedule:
    # Runs "everyday at 11 AM IST ( 5:30 UTC timezone)" (see https://crontab.guru)
    - cron: '30 5 * * *'
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          
      - name: microservice name
        run: echo "${{ github.event.inputs.mservice }}"
        
        
      - name: Cypress.io
        uses: ./
        with:
          build: npx cypress info
        

      - name: Npm with no scheduler 
        if: ${{ github.event_name != 'schedule' }}
        uses: ebomart/npm-test-action@main
        with:
          ENV_Name: staging
          Microservice_name: ${{ github.event.inputs.mservice }}
      

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@4cf605e31141e43479bff86bc4e3a5b642bedaa3
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
        
      



      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # Required mail server address:
      #     server_address: in-v3.mailjet.com
      #     # Required mail server port:
      #     server_port: 587
      #     # Optional (recommended): mail server username:
      #     username: ${{secrets.MAIL_USERNAME}}
      #     # Optional (recommended) mail server password:
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     # Required mail subject:
      #     subject: Github Actions job result
      #     # Required recipients' addresses:
      #     to: pankaj.h@cloverbaytechnologies.com
      #     # Required sender full name (address can be skipped):
      #     from: systemadmin
      #     # Optional whether this connection use TLS (default is true if server_port is 465)
      #     secure: false
      #     # Optional plain body:
      #     body: Build job of ${{github.repository}} completed successfully! , report link http://swagger.ibo.com/ibo-bff-automation/
      #     # Optional HTML body read from file:
      #     # html_body: file://allure-report/index.html
      #     # Optional carbon copy recipients:
      #     # cc: kyloren@example.com,leia@example.com
      #     # # Optional blind carbon copy recipients:
      #     # bcc: r2d2@example.com,hansolo@example.com
      #     # # Optional recipient of the email response:
      #     # reply_to: luke@example.com
      #     # # Optional Message ID this message is replying to:
      #     # in_reply_to: <random-luke@example.com>
      #     # Optional unsigned/invalid certificates allowance:
      #     ignore_cert: true
      #     # Optional converting Markdown to HTML (set content_type to text/html too):
      #     convert_markdown: true
      #     # # Optional attachments:
      #     # attachments: ./allure-report/*.js
      #     # # Optional priority: 'high', 'normal' (default) or 'low'
      #     priority: low 
